-- PENDENTE REFATORACAO (LINGUA)
-- Criação da estrutura do banco de controle repldb.fdb
CREATE TABLE planos_replicacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origem VARCHAR(255) NOT NULL,
    destino VARCHAR(255) NOT NULL,
    tipo_replicacao VARCHAR(20) DEFAULT 'backup_restore',
    agendamento VARCHAR(100),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE log_replicacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plano_id INTEGER NOT NULL,
    inicio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fim TIMESTAMP,
    status VARCHAR(20),
    mensagem VARCHAR(500),
    FOREIGN KEY (plano_id) REFERENCES planos_replicacao(id) ON DELETE CASCADE
);

-- Procedure para registrar logs (opcional se usar insert direto via C++)
SET TERM !! ;
CREATE OR ALTER PROCEDURE registrar_log (
    plano_id INTEGER,
    status VARCHAR(20),
    mensagem VARCHAR(500)
)
AS
BEGIN
    INSERT INTO log_replicacao (plano_id, status, mensagem) 
    VALUES (:plano_id, :status, :mensagem);
END!!
SET TERM ; !!

