-- db/init.sql

-- Criação da tabela de planos de replicação
CREATE TABLE planos_replicacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fonte VARCHAR(255) NOT NULL,
    destino VARCHAR(255) NOT NULL,
    ativo BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Criação da tabela de logs de replicação
CREATE TABLE log_replicacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plano_id INTEGER NOT NULL,
    datahora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mensagem VARCHAR(1024),
    FOREIGN KEY (plano_id) REFERENCES planos_replicacao(id)
);
